# Generated by Django 5.2.5 on 2025-08-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='longitud',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_operacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta')], default='venta', max_length=10),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
