# Generated by Django 5.2.5 on 2025-08-27 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Propiedad',
        ),
    ]
