# Generated by Django 5.2.5 on 2025-08-27 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_delete_propiedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
        migrations.AddField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Número inválido. Usa 10 dígitos (ej. 6561234567) o formato +5216561234567.', regex='^(\\+?52)?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='RFC inválido. Ejemplo persona: GODE561231GR8 / empresa: ABC001231AB1 (usar MAYÚSCULAS).', regex='^([A-ZÑ&]{3}\\d{6}[A-Z0-9]{3}|[A-ZÑ&]{4}\\d{6}[A-Z0-9]{3})$')]),
        ),
    ]
