# Generated by Django 4.2 on 2025-10-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_remove_perfil_ciudad_remove_perfil_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene una suscripción activa en Stripe.'),
        ),
    ]
