# Generated by Django 4.2 on 2025-10-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_perfil_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='stripe_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='stripe_status',
            field=models.CharField(blank=True, choices=[('incomplete', 'incomplete'), ('incomplete_expired', 'incomplete_expired'), ('trialing', 'trialing'), ('active', 'active'), ('past_due', 'past_due'), ('canceled', 'canceled'), ('unpaid', 'unpaid'), (None, 'None')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Compatibilidad: indica si se detecta una suscripción activa (se sincroniza desde Stripe).'),
        ),
    ]
