# Generated by Django 5.2.5 on 2025-08-29 21:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta')], max_length=10)),
                ('recamaras', models.PositiveIntegerField(default=0)),
                ('banos', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('estacionamientos', models.PositiveIntegerField(default=0)),
                ('metros_construccion', models.PositiveIntegerField(default=0)),
                ('metros_terreno', models.PositiveIntegerField(default=0)),
                ('tipo_financiamiento', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito'), ('ambos', 'Ambos')], default='ambos', max_length=12)),
                ('calle', models.CharField(max_length=120)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('colonia', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=120)),
                ('codigo_postal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe tener exactamente 5 dígitos.', regex='^\\d{5}$')])),
                ('latitud', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitud', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('estatus', models.CharField(choices=[('disponible', 'Disponible'), ('en_trato', 'En trato'), ('cerrada', 'Vendida/Rentada')], default='disponible', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_creacion',),
            },
        ),
        migrations.CreateModel(
            name='FotoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicaciones/%Y/%m/%d/')),
                ('es_portada', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='publicaciones.publicacion')),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['estatus'], name='publicacion_estatus_1f3354_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['tipo_operacion'], name='publicacion_tipo_op_9ab182_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['ciudad', 'estado'], name='publicacion_ciudad_518bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['precio'], name='publicacion_precio_21c11a_idx'),
        ),
        migrations.AddIndex(
            model_name='fotopublicacion',
            index=models.Index(fields=['publicacion', 'orden'], name='publicacion_publica_b8e227_idx'),
        ),
    ]
