# Generated by Django 5.2.5 on 2025-08-29 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen_portada',
            field=models.ImageField(blank=True, help_text='Imagen destacada opcional para mostrar en listados', null=True, upload_to='publicaciones/portadas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_financiamiento',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito'), ('ambos', 'Crédito o contado')], default='ambos', max_length=12),
        ),
    ]
