# Generated by Django 5.2.5 on 2025-08-30 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_publicacion_imagen_portada_alter_publicacion_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen_portada',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='latitud',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='longitud',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
