# Generated by Django 4.2 on 2025-08-28 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(help_text='Dirección de la propiedad.', max_length=255),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(default='disponible', help_text='Estado de la propiedad (ej. disponible, en trato, vendida).', max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_operacion',
            field=models.CharField(help_text='Tipo de operación: renta o venta.', max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(help_text='Título descriptivo de la propiedad.', max_length=255),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='vendedor',
            field=models.ForeignKey(help_text='Usuario vendedor al que pertenece la propiedad.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
